=== pantczak/XML-Technologies-Assignments/Task-1/music.dtd
<?xml encoding="UTF-8"?>
        <!ELEMENT albums (authors,bandlist,album+)>
        <!ELEMENT authors (author)+>
        <!ELEMENT bandlist (bandinfo*)>
        <!ELEMENT bandinfo (name)>
        <!ELEMENT name (#PCDATA)>
        <!ATTLIST bandinfo band_id ID #REQUIRED>
        <!ELEMENT album (info,pic1,songs)>
        <!ATTLIST album genre_type NMTOKEN #REQUIRED>
        <!ATTLIST album type (Vinyl|CD) #IMPLIED>
        <!ATTLIST album id NMTOKEN #REQUIRED>
        <!ELEMENT info (album_title,band,studio,release_year,number_of_songs,total_length,number_of_disks,rating,price)>
        <!ELEMENT album_title (#PCDATA)>
        <!ELEMENT band (#PCDATA)>
        <!ATTLIST band band_id IDREF #IMPLIED>
        <!ELEMENT studio (#PCDATA)>
        <!ELEMENT release_year (#PCDATA)>
        <!ELEMENT number_of_songs (#PCDATA)>
        <!ELEMENT total_length (#PCDATA)>
        <!ELEMENT number_of_disks (#PCDATA)>
        <!ELEMENT rating (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT pic1 (#PCDATA)>
        <!ATTLIST pic1 id NMTOKEN #IMPLIED>
        <!ELEMENT songs (song+)>
        <!ELEMENT song (title,song_length)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT song_length (#PCDATA)>
        <!ELEMENT author (authorName,authorSurname,authorindex)>
        <!ATTLIST author id NMTOKEN #REQUIRED>
        <!ELEMENT authorName (#PCDATA)>
        <!ELEMENT authorSurname (#PCDATA)>
        <!ELEMENT authorindex (#PCDATA)>

=== pantczak/XML-Technologies-Assignments/Task-1/music.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/css" href="music.css"?>
<!DOCTYPE albums SYSTEM "music.dtd">

<albums>
    <authors>
        <author id="Piter">
            <authorName>Piotr</authorName>
            <authorSurname>Antczak</authorSurname>
            <authorindex>224248</authorindex>
        </author>
        <author id="Mikolaj">
            <authorName>Mikołaj</authorName>
            <authorSurname>Bajkowski</authorSurname>
            <authorindex>224251</authorindex>
        </author>
    </authors>
    <!--BANDS/WYKONAWCY-->
    <bandlist>
        <bandinfo band_id="BKeys">
            <name>The Black Keys></name>
        </bandinfo>
        <bandinfo band_id="Weezer">
            <name>Weezer</name>
        </bandinfo>
        <bandinfo band_id="DPunk">
            <name>Daft Punk</name>
        </bandinfo>
        <bandinfo band_id="LLan">
            <name>Łąki Łan</name>
        </bandinfo>
        <bandinfo band_id="Avicii">
            <name>Avicii</name>
        </bandinfo>
        <bandinfo band_id="MJackson">
            <name>Michael Jackson</name>
        </bandinfo>
        <bandinfo band_id="ATC">
            <name>Against The Current</name>
        </bandinfo>
        <bandinfo band_id="FMac">
            <name>Fletwood Mac</name>
        </bandinfo>
        <bandinfo band_id="EJohn">
            <name>Elton John</name>
        </bandinfo>
        <bandinfo band_id="Slip">
            <name>Slipknot</name>
        </bandinfo>
        <bandinfo band_id="BMarley">
            <name>Bob Marley</name>
        </bandinfo>
        <bandinfo band_id="MDavis">
            <name>Miles Davis</name>
        </bandinfo>
        <bandinfo band_id="Muse">
            <name>Muse</name>
        </bandinfo>
    </bandlist>
    <!--Collection/Kolekcja płyt-->
    <album genre_type="Rock" type="Vinyl" id="A1">
        <info>
            <album_title>Let's Rock</album_title>
            <band band_id="BKeys">The Black Keys</band>
            <studio>Easy Eye Sound</studio>
            <release_year>28-06-2019</release_year>
            <number_of_songs>12</number_of_songs>
            <total_length>38:30</total_length>
            <number_of_disks>1</number_of_disks>
            <rating>8.77</rating>
            <price>80.00</price>
        </info>
        <pic1 id="LR"/>
        <songs>
            <song>
                <title>Shine A Little Light</title>
                <song_length>3:17</song_length>
            </song>
            <song>
                <title>Eagle Birds</title>
                <song_length>2:41</song_length>
            </song>
            <song>
                <title>Lo/Hi</title>
                <song_length>2:58</song_length>
            </song>
            <song>
                <title>Walk Across the Water</title>
                <song_length>3:56</song_length>
            </song>
            <song>
                <title>Tell me Lies</title>
                <song_length>3:40</song_length>
            </song>
            <song>
                <title>Every Little Thing</title>
                <song_length>3:20</song_length>
            </song>
            <song>
                <title>Get Yourself Together</title>
                <song_length>3:57</song_length>
            </song>
            <song>
                <title>Sit Around and Miss You</title>
                <song_length>2:41</song_length>
            </song>
            <song>
                <title>Go</title>
                <song_length>2:27</song_length>
            </song>
            <song>
                <title>Breaking Down</title>
                <song_length>3:25</song_length>
            </song>
            <song>
                <title>Under the Gun</title>
                <song_length>3:16</song_length>
            </song>
            <song>
                <title>Fire Walk with Me</title>
                <song_length>2:58</song_length>
            </song>
        </songs>
    </album>
    <album genre_type="Rock" type="CD" id="A2">
        <info>
            <album_title>El Camino</album_title>
            <band band_id="BKeys">The Black Keys</band>
            <studio>Nonesuch Records</studio>
            <release_year>02-12-2011</release_year>
            <number_of_songs>11</number_of_songs>
            <total_length>37:42</total_length>
            <number_of_disks>1</number_of_disks>
            <rating>8.90</rating>
            <price>45.00</price>
        </info>
        <pic1 id="EC"/>
        <songs>
            <song>
                <title>Lonley Boy</title>
                <song_length>3:13</song_length>
            </song>
            <song>
                <title>Dead and Gone</title>
                <song_length>3:41</song_length>
            </song>
            <song>
                <title>Cold on the Ceiling</title>
                <song_length>2:44</song_length>
            </song>
            <song>
                <title>Little black Submarines</title>
                <song_length>4:11</song_length>
            </song>
            <song>
                <title>Money Maker</title>
                <song_length>2:57</song_length>
            </song>
            <song>
                <title>Run Right Back</title>
                <song_length>3:17</song_length>
            </song>
            <song>
                <title>Sister</title>
                <song_length>3:25</song_length>
            </song>
            <song>
                <title>Hello of a Season</title>
                <song_length>3:45</song_length>
            </song>
            <song>
                <title>Stop Stop</title>
                <song_length>3:30</song_length>
            </song>
            <song>
                <title>Nova Baby</title>
                <song_length>3:27</song_length>
            </song>
            <song>
                <title>Mind Eraser</title>
                <song_length>3:15</song_length>
            </song>
        </songs>
    </album>
    <album genre_type="Rock" type="Vinyl" id="A3">
        <info>
            <album_title>Turn Blue</album_title>
            <band band_id="BKeys">The Black Keys</band>
            <studio>Nonesuch Records</studio>
            <release_year>12-05-2014</release_year>
            <number_of_songs>11</number_of_songs>
            <total_length>45:09</total_length>
            <number_of_disks>1</number_of_disks>
            <rating>7.90</rating>
            <price>75.00</price>
        </info>
        <pic1 id="TB"/>
        <songs>
            <song>
                <title>Weight of Love</title>
                <song_length>6:50</song_length>
            </song>
            <song>
                <title>In Time</title>
                <song_length>4:28</song_length>
            </song>
            <song>
                <title>Turn Blue</title>
                <song_length>3:42</song_length>
            </song>
            <song>
                <title>Fever</title>
                <song_length>4:06</song_length>
            </song>
            <song>
                <title>Year in Review</title>
                <song_length>3:48</song_length>
            </song>
            <song>
                <title>Bullet in the Brain</title>
                <song_length>4:15</song_length>
            </song>
            <song>
                <title>It's Up to You Now</title>
                <song_length>3:10</song_length>
            </song>
            <song>
                <title>Waiting in Words</title>
                <song_length>3:37</song_length>
            </song>
            <song>
                <title>10 Lovers</title>
                <song_length>3:33</song_length>
            </song>
            <song>
                <title>In our Prime</title>
                <song_length>4:38</song_length>
            </song>
            <song>
                <title>Gotta Get Away</title>
                <song_length>3:02</song_length>
            </song>
        </songs>
    </album>
    <album genre_type="Rock" type="CD" id="A4">
        <info>
            <album_title>Weezer</album_title>
            <band band_id="Weezer">Weezer</band>
            <studio>Crush Music, Atlantic Records</studio>
            <release_year>01-03-2019</release_year>
            <number_of_songs>10</number_of_songs>
            <total_length>37:33</total_length>
            <number_of_disks>1</number_of_disks>
            <rating>8.03</rating>
            <price>45.00</price>
        </info>
        <pic1 id="WR"/>
        <songs>
            <song>
                <title>Can't Knock the Hustle</title>
                <song_length>3:35</song_length>
            </song>
            <song>
                <title>Zombie Bastards</title>
                <song_length>4:11</song_length>
            </song>
            <song>
                <title>High as a Kite</title>
                <song_length>3:48</song_length>
            </song>
            <song>
                <title>Living in L.A.</title>
                <song_length>3:38</song_length>
            </song>
            <song>
                <title>Piece of Cake</title>
                <song_length>3:17</song_length>
            </song>
            <song>
                <title>I'm Just Being Honest</title>
                <song_length>3:57</song_length>
            </song>
            <song>
                <title>Too Many Thoughts in My Head</title>
                <song_length>4:03</song_length>
            </song>
            <song>
                <title>The Prince Who Wanted Everything</title>
                <song_length>3:23</song_length>
            </song>
            <song>
                <title>Byzantine</title>
                <song_length>4:09</song_length>
            </song>
            <song>
                <title>California Snow</title>
                <song_length>3:32</song_length>
            </song>
        </songs>
    </album>
