=== pantczak/XML-Technologies-Assignments/Task-2/music.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="albums"
            xmlns:albums="albums">

    <xsd:element type="albums:mainType" name="albums">

        <xsd:key name="key_band_id">
            <xsd:selector xpath="./albums:bandlist/albums:bandinfo"/>
            <xsd:field xpath="@band_id"/>
        </xsd:key>

        <xsd:key name="key_id">
            <xsd:selector xpath="./albums:albumlist/albums:album"/>
            <xsd:field xpath="@id"/>
        </xsd:key>

        <xsd:key name="key_p_id">
            <xsd:selector xpath="./albums:albumlist/albums:album/albums:pic1"/>
            <xsd:field xpath="@p_id"/>
        </xsd:key>

        <xsd:keyref name="keyref_band_id" refer="albums:key_band_id">
            <xsd:selector xpath="./albums:albumlist/albums:album/albums:info/albums:band"/>
            <xsd:field xpath="@band_id_ref"/>
        </xsd:keyref>

    </xsd:element>

    <xsd:complexType name="mainType">
        <xsd:sequence>
            <xsd:element type="albums:authorType" name="authors"/>
            <xsd:element type="albums:bandsType" name="bandlist"/>
            <xsd:element type="albums:albumsType" name="albumlist"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="authorType">
        <xsd:sequence maxOccurs="2" minOccurs="1">
            <xsd:element name="author" type="albums:author_info"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="author_info">
        <xsd:group ref="albums:authorinfo"/>
    </xsd:complexType>

    <xsd:group name="authorinfo">
        <xsd:sequence>
            <xsd:element name="authorName" type="xsd:token"/>
            <xsd:element name="authorSurname" type="xsd:token"/>
            <xsd:element name="authorindex">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:pattern value="([2][0-9][0-9][0-9][0-9][0-9])"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:group>


    <xsd:complexType name="bandsType">
        <xsd:sequence>
            <xsd:element name="bandinfo" minOccurs="1" maxOccurs="unbounded" type="albums:bandType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="bandType">
        <xsd:sequence>
            <xsd:element name="name">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength value="50"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="band_id" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:token">
                    <xsd:pattern value="([A-Z]([a-z]|[A-Z]){3})"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="albumsType">
        <xsd:sequence>
            <xsd:element type="albums:albumType" name="album" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="albumType">
        <xsd:sequence>
            <xsd:element type="albums:infoType" name="info"/>
            <xsd:element name="pic1">
                <xsd:complexType>
                    <xsd:attribute name="p_id" use="optional"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element type="albums:songsType" name="songs"/>
        </xsd:sequence>
        <xsd:attribute name="genre_type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Rock"/>
                    <xsd:enumeration value="Electronic"/>
                    <xsd:enumeration value="House"/>
                    <xsd:enumeration value="Pop"/>
                    <xsd:enumeration value="Metal"/>
                    <xsd:enumeration value="Reggae"/>
                    <xsd:enumeration value="Jazz"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="type" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:token">
                    <xsd:enumeration value="CD"/>
                    <xsd:enumeration value="Vinyl"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="id" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:token">
                    <xsd:pattern value="([A-Z][0-9][0-9]?)"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="infoType">
        <xsd:sequence>
            <xsd:element name="album_title">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength value="60"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="band" type="albums:infoinbandType"/>
            <xsd:element name="studio">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="release_year">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:date"/>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="number_of_songs" type="xsd:positiveInteger"/>
            <xsd:element name="total_length" type="xsd:time"/>
            <xsd:element name="number_of_disks" type="xsd:positiveInteger" default="1"/>
            <xsd:element name="serial_number">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="(CD-[0-9]{5}-[A-Z][A-Z][0-9])"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element maxOccurs="1" name="shop_id">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="([0-9]{3}[A-Z][0-9]{2}[A-Z])"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="rating">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:decimal">
                        <xsd:fractionDigits value="1"/>
                        <xsd:maxInclusive value="10"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="price" default="45.00">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:decimal">
                        <xsd:fractionDigits value="2"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="infoinbandType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="band_id_ref" type="xsd:token"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="songsType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="song" type="albums:songtype"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="songtype">
        <xsd:sequence>
            <xsd:element name="title">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength value="100"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="song_length">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="([0-9]:([0-9][0-9]))"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== pantczak/XML-Technologies-Assignments/Task-3/music.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="music.xsl"?>

<!--<albums xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"-->
<!--        xsi:schemaLocation="albums music.xsd"-->
<!--        xmlns="albums">-->
<albums>
    <authors>
        <author>
            <authorName>Piotr</authorName>
            <authorSurname>Antczak</authorSurname>
            <authorindex>224248</authorindex>
        </author>
        <author>
            <authorName>Mikołaj</authorName>
            <authorSurname>Bajkowski</authorSurname>
            <authorindex>224251</authorindex>
        </author>
    </authors>
    <bandlist>
        <bandinfo band_id="BKey">
            <name>The Black Keys</name>
        </bandinfo>
        <bandinfo band_id="Weez">
            <name>Weezer</name>
        </bandinfo>
        <bandinfo band_id="DPun">
            <name>Daft Punk</name>
        </bandinfo>
        <bandinfo band_id="LL">
            <name>Laki Lan</name>
        </bandinfo>
        <bandinfo band_id="Avic">
            <name>Avicii</name>
        </bandinfo>
        <bandinfo band_id="MJac">
            <name>Michael Jackson</name>
        </bandinfo>
        <bandinfo band_id="ATCu">
            <name>Against The Current</name>
        </bandinfo>
        <bandinfo band_id="FMac">
            <name>Fletwood Mac</name>
        </bandinfo>
        <bandinfo band_id="EJoh">
            <name>Elton John</name>
        </bandinfo>
        <bandinfo band_id="Slip">
            <name>Slipknot</name>
        </bandinfo>
        <bandinfo band_id="BMar">
            <name>Bob Marley</name>
        </bandinfo>
        <bandinfo band_id="MDav">
            <name>Miles Davis</name>
        </bandinfo>
        <bandinfo band_id="Muse">
            <name>Muse</name>
        </bandinfo>
    </bandlist>
    <!--Collection/Kolekcja płyt-->
    <albumlist>
        <album genre_type="Rock" type="Vinyl" id="A1">
            <info>
                <album_title>Let's Rock</album_title>
                <band band_id_ref="BKey">The Black Keys</band>
                <studio>Easy Eye Sound</studio>
                <release_year>2019-06-28</release_year>
                <number_of_songs> 12 </number_of_songs>
                <total_length>00:38:30</total_length>
                <number_of_disks>1</number_of_disks>
                <serial_number>CD-22345-AA4</serial_number>
                <shop_id>234P45Y</shop_id>
                <rating>8.7</rating>
                <price>80.00</price>
            </info>
            <pic1 p_id="LR"/>
            <songs>
                <song>
                    <title>Shine A Little Light</title>
                    <song_length>3:17</song_length>
                </song>
                <song>
                    <title>Eagle Birds</title>
                    <song_length>2:41</song_length>
                </song>
                <song>
                    <title>Lo/Hi</title>
                    <song_length>2:58</song_length>
                </song>
                <song>
                    <title>Walk Across the Water</title>
                    <song_length>3:56</song_length>
                </song>
                <song>
                    <title>Tell me Lies</title>
                    <song_length>3:40</song_length>
                </song>
                <song>
                    <title>Every Little Thing</title>
                    <song_length>3:20</song_length>
                </song>
                <song>
                    <title>Get Yourself Together</title>
                    <song_length>3:57</song_length>
                </song>
                <song>
                    <title>Sit Around and Miss You</title>
                    <song_length>2:41</song_length>
                </song>
                <song>
                    <title>Go</title>
                    <song_length>2:27</song_length>
                </song>
                <song>
                    <title>Breaking Down</title>
                    <song_length>3:25</song_length>
                </song>
                <song>
                    <title>Under the Gun</title>
                    <song_length>3:16</song_length>
                </song>
                <song>
                    <title>Fire Walk with Me</title>
                    <song_length>2:58</song_length>
                </song>
            </songs>
        </album>
        <album genre_type="Rock" type="CD" id="A2">
            <info>
                <album_title>El Camino</album_title>
                <band band_id_ref="BKey">The Black Keys</band>
                <studio>Nonesuch Records</studio>
                <release_year>2011-12-02</release_year>
                <number_of_songs>11</number_of_songs>
                <total_length>00:37:42</total_length>
                <number_of_disks>1</number_of_disks>
                <serial_number>CD-27325-AA4</serial_number>
                <shop_id>368B67U</shop_id>
                <rating>8.9</rating>
                <price>45.00</price>
            </info>
            <pic1 p_id="EC"/>
            <songs>
                <song>
                    <title>Lonley Boy</title>
                    <song_length>3:13</song_length>
                </song>
                <song>
                    <title>Dead and Gone</title>
                    <song_length>3:41</song_length>
                </song>
                <song>
                    <title>Cold on the Ceiling</title>
                    <song_length>2:44</song_length>
                </song>
                <song>
                    <title>Little black Submarines</title>
                    <song_length>4:11</song_length>
                </song>
                <song>
                    <title>Money Maker</title>
                    <song_length>2:57</song_length>
                </song>
                <song>
                    <title>Run Right Back</title>
                    <song_length>3:17</song_length>
                </song>
                <song>
                    <title>Sister</title>
                    <song_length>3:25</song_length>
                </song>
                <song>
                    <title>Hello of a Season</title>
                    <song_length>3:45</song_length>
                </song>
                <song>
                    <title>Stop Stop</title>
                    <song_length>3:30</song_length>
                </song>
                <song>
                    <title>Nova Baby</title>
                    <song_length>3:27</song_length>
                </song>
                <song>
                    <title>Mind Eraser</title>
                    <song_length>3:15</song_length>
                </song>
            </songs>
        </album>
        <album genre_type="Rock" type="Vinyl" id="A3">
            <info>
                <album_title>Turn Blue</album_title>
                <band band_id_ref="BKey">The Black Keys</band>
                <studio>Nonesuch Records</studio>
                <release_year>2014-05-12</release_year>
                <number_of_songs>11</number_of_songs>
                <total_length>00:45:09</total_length>
                <number_of_disks>1</number_of_disks>
                <serial_number>CD-22925-AA4</serial_number>
                <shop_id>368B67U</shop_id>
                <rating>7.9</rating>
                <price>75.00</price>
            </info>
            <pic1 p_id="TB"/>
            <songs>
                <song>
                    <title>Weight of Love</title>
                    <song_length>6:50</song_length>
                </song>
                <song>
                    <title>In Time</title>
                    <song_length>4:28</song_length>
                </song>
                <song>
                    <title>Turn Blue</title>
                    <song_length>3:42</song_length>
                </song>
                <song>
                    <title>Fever</title>
                    <song_length>4:06</song_length>
                </song>
                <song>
                    <title>Year in Review</title>
                    <song_length>3:48</song_length>
                </song>
                <song>
                    <title>Bullet in the Brain</title>
                    <song_length>4:15</song_length>
                </song>
                <song>
                    <title>It's Up to You Now</title>
                    <song_length>3:10</song_length>
                </song>
                <song>
                    <title>Waiting in Words</title>
                    <song_length>3:37</song_length>
                </song>
                <song>
                    <title>10 Lovers</title>
                    <song_length>3:33</song_length>
                </song>
                <song>
                    <title>In our Prime</title>
                    <song_length>4:38</song_length>
                </song>
                <song>
                    <title>Gotta Get Away</title>
                    <song_length>3:02</song_length>
                </song>
            </songs>
        </album>
        <album genre_type="Rock" type="CD" id="A4">
            <info>
                <album_title>Weezer</album_title>
                <band band_id_ref="Weez">Weezer</band>
                <studio>Crush Music, Atlantic Records</studio>
                <release_year>2019-03-01</release_year>
                <number_of_songs>10</number_of_songs>
                <total_length>00:37:33</total_length>
                <number_of_disks>1</number_of_disks>
                <serial_number>CD-12745-DA4</serial_number>
                <shop_id>588Z34H</shop_id>
                <rating>8.3</rating>
                <price>45.00</price>
            </info>
            <pic1 p_id="WR"/>
            <songs>
                <song>
                    <title>Can't Knock the Hustle</title>
                    <song_length>3:35</song_length>
